/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    App: typeof import('./resources/js/Pages/App.vue')['default']
    ApplicationLogo: typeof import('./resources/js/Components/ApplicationLogo.vue')['default']
    BreezeAuthenticatedLayout: typeof import('./resources/js/Layouts/BreezeAuthenticatedLayout.vue')['default']
    BtnDelete: typeof import('./resources/js/Components/Yogas/BtnDelete.vue')['default']
    BtnDeleteReservation: typeof import('./resources/js/Components/Yogas/BtnDeleteReservation.vue')['default']
    Button: typeof import('./resources/js/Components/Button.vue')['default']
    Checkbox: typeof import('./resources/js/Components/Checkbox.vue')['default']
    CheckIcon: typeof import('./resources/js/Components/Yogas/CheckIcon.vue')['default']
    ConfirmPassword: typeof import('./resources/js/Pages/Auth/ConfirmPassword.vue')['default']
    DateSlot: typeof import('./resources/js/Components/Yogas/DateSlot.vue')['default']
    Dropdown: typeof import('./resources/js/Components/Dropdown.vue')['default']
    DropdownLink: typeof import('./resources/js/Components/DropdownLink.vue')['default']
    ForgotPassword: typeof import('./resources/js/Pages/Auth/ForgotPassword.vue')['default']
    GroupSlot: typeof import('./resources/js/Components/Yogas/GroupSlot.vue')['default']
    Guest: typeof import('./resources/js/Layouts/Guest.vue')['default']
    Input: typeof import('./resources/js/Components/Input.vue')['default']
    InputError: typeof import('./resources/js/Components/InputError.vue')['default']
    Label: typeof import('./resources/js/Components/Label.vue')['default']
    Login: typeof import('./resources/js/Pages/Auth/Login.vue')['default']
    NavLink: typeof import('./resources/js/Components/NavLink.vue')['default']
    NewDate: typeof import('./resources/js/Components/Yogas/NewDate.vue')['default']
    NewUser: typeof import('./resources/js/Components/Yogas/NewUser.vue')['default']
    Register: typeof import('./resources/js/Pages/Auth/Register.vue')['default']
    ResetPassword: typeof import('./resources/js/Pages/Auth/ResetPassword.vue')['default']
    ResponsiveNavLink: typeof import('./resources/js/Components/ResponsiveNavLink.vue')['default']
    TheDate: typeof import('./resources/js/Components/Yogas/TheDate.vue')['default']
    TheGroup: typeof import('./resources/js/Components/Yogas/TheGroup.vue')['default']
  }
}
