// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ApplicationLogo: typeof import('./resources/js/Components/ApplicationLogo.vue')['default']
    Authenticated: typeof import('./resources/js/Layouts/Authenticated.vue')['default']
    BreezeAuthenticatedLayout: typeof import('./resources/js/Layouts/BreezeAuthenticatedLayout.vue')['default']
    Button: typeof import('./resources/js/Components/Button.vue')['default']
    Checkbox: typeof import('./resources/js/Components/Checkbox.vue')['default']
    ConfirmPassword: typeof import('./resources/js/Pages/Auth/ConfirmPassword.vue')['default']
    Dashboard: typeof import('./resources/js/Pages/Dashboard.vue')['default']
    DateInsa: typeof import('./resources/js/Components/Yogas/DateInsa.vue')['default']
    DateYoga: typeof import('./resources/js/Components/Yogas/DateYoga.vue')['default']
    Dropdown: typeof import('./resources/js/Components/Dropdown.vue')['default']
    DropdownLink: typeof import('./resources/js/Components/DropdownLink.vue')['default']
    ForgotPassword: typeof import('./resources/js/Pages/Auth/ForgotPassword.vue')['default']
    Guest: typeof import('./resources/js/Layouts/Guest.vue')['default']
    HomePage: typeof import('./resources/js/Pages/HomePage.vue')['default']
    Input: typeof import('./resources/js/Components/Input.vue')['default']
    InputError: typeof import('./resources/js/Components/InputError.vue')['default']
    Label: typeof import('./resources/js/Components/Label.vue')['default']
    Login: typeof import('./resources/js/Pages/Auth/Login.vue')['default']
    NavLink: typeof import('./resources/js/Components/NavLink.vue')['default']
    NewDate: typeof import('./resources/js/Components/Yogas/NewDate.vue')['default']
    NewUser: typeof import('./resources/js/Components/Yogas/NewUser.vue')['default']
    Register: typeof import('./resources/js/Pages/Auth/Register.vue')['default']
    ResetPassword: typeof import('./resources/js/Pages/Auth/ResetPassword.vue')['default']
    ResponsiveNavLink: typeof import('./resources/js/Components/ResponsiveNavLink.vue')['default']
    VerifyEmail: typeof import('./resources/js/Pages/Auth/VerifyEmail.vue')['default']
    Welcome: typeof import('./resources/js/Pages/Welcome.vue')['default']
  }
}
